name: flutter_calendar
description: A calendar widget that uses Material Design.
version: 0.0.8+1
homepage: https://github.com/apptreesoftware/flutter_calendar

environment:
  sdk: '>=2.12.0 <3.0.0'

publish_to: none
dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  tuple: ^2.0.1
  date_utils:
    git:
      url: https://github.com/pabloamg/date_utils.git
      ref: 04cebd1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
